spring:
    datasource:
        url: jdbc:mysql://68.178.163.174:3306/isoil_db
        username: root
        password: Fizar#123
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER

    
    jpa:
      hibernate:
        ddl-auto: update

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    
    # jpa:
    #   properties:
    #     hibernate:
    #       dialect: org.hibernate.dialect.MySQL5Dialect
    
    jpa.hibernate.ddl_auto: create

file:
  upload-dir: ./uploads